sudo: required

language: java

services:
  - docker

after_success:
  - docker network create --driver bridge sem
  - docker pull mongo
  - docker run -d --name mongo-dbserver --network sem mongo
  - docker build -t sem .
  - docker run --network sem sem